### PR TITLE
enable server avatar & added ntfy support & added slack support

### PR DESCRIPTION
**Pull request by bjornclauw**
Hi, 
I'm using monocker on different servers. Added an avatar URL to make it easier to see from what server the message originated.
I use discord as a platform. I tried looking into the others (pushbullet, telegram, pushover), seems this is not possible to easily implement on the other platforms.

(also supported by NTFY mobile and slack now)

image

When commenting out the variable in the docker-compose.yml file, the option is ignored.

### CODE REVIEW

**Comment by bjornclauw** [comment]
Also, added NTFY support

**Comment by bjornclauw** [comment]
Also, added slack support

**Comment by bjornclauw** [comment]
error_msg
error_msg2

**Comment by jeffreyswiggins** [comment]
sweet... thank you @bjornclauw if this gets added and works.  I have a Discord setup for just Monocker because everything else uses my Slack channel.  I used to use Discord for everything but find the alerts were getting sometimes as delayed as a hour after they occurred, so moved to Slack.

**Comment by petersem** [comment]
@bjornclauw I am so sorry that i didnt see this earlier. I will look to implement after some testing.

**Pull request merged**
